config/routes.rb
Rails.application.routes.draw do
  root to: "feeds#index"

  resources :feeds do
    resources :entries
    resources :skins
  end

  get '/refresh_news', to: 'feeds#refresh_news'
  get '/refresh_skins', to: 'feeds#refresh_skins'
  get '/publish_news', to: 'entries#publish'
  get '/publish_skins', to: 'skins#publish'

end

app/models/feed.rb
class Feed < ApplicationRecord
  has_many :entries
  has_many :skins
end

app/controllers/feeds_controller.rb
require 'uri'
require 'feedjira'
require 'httparty'
require 'faraday'
require 'nokogiri'
require 'json'

class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy ]

  SHOP_API_URL = 'https://api.steampowered.com/ISteamEconomy/GetAssetPrices/v1/'
  SHOP_API_KEY = ENV["STEAM_API_KEY"]
  SHOP_URL = "https://store.steampowered.com/itemstore/252490/browse/?filter=All"

  def index
    @feeds = Feed.all
  end

  def show
  end

  def new
    @feed = Feed.new
  end

  def edit
  end

  def create
    @feed = Feed.new(feed_params)

    if @feed.save
      redirect_to @feed, notice: 'Feed was successfully created.'
    else
      render :new
    end
  end

  def update
    if @feed.update(feed_params)
      redirect_to @feed, notice: 'Feed was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    if @feed.destroy
      redirect_to feeds_url, notice: 'Feed was successfully destroyed.'
    end
  end

  def refresh_news
    @message = String.new
    Feed.all.each do | feed |
      if feed.pullurl
        if feed.pullurl =~ URI::regexp
          @message << "start syncing #{feed.title} <br>"
          xml = HTTParty.get(feed.pullurl).body
          content = Feedjira.parse(xml)
          content.entries.each do | remote_entry |
            local_entry = feed.entries.where(link1: remote_entry.entry_id).first_or_initialize
            local_entry.description = remote_entry.summary
            local_entry.title = remote_entry.title
            local_entry.feed = feed
            local_entry.save!
              if local_entry.errors.any?
                local_entry.errors.each do |e|
                  @message << e.to_s
                end
              end
            @message << " --- Synced Entry - #{remote_entry.title} <br>"
          end
          @message << " --- done syncing #{feed.title} <br>"
        else
          @message << " --- skipping #{feed.title}, pullurl is not an url <br>"
        end
      else
        @message << " --- skipping #{feed.title}, no pullurl <br>"
      end
    end
  end

  def refresh_skins
    @message = String.new
    Feed.all.each do | feed |
      if feed.pullurl
        if feed.pullurl =~ URI::regexp
	  if feed.gameid
            @message << "START syncing #{feed.title}, ID #{feed.gameid} <br>"

            app = feed.gameid
            resp = Faraday.get(SHOP_API_URL, {key: SHOP_API_KEY, appid: app}, {'Accept' => 'application/json'})

            j = JSON.parse(resp.body)
            prices = Hash.new
            j["result"]["assets"].each do |item|
              itemid = item["name"].to_s
              prices[itemid] = Hash.new
              rappen = item["prices"]["CHF"]
              prices[itemid]["CHF"] = rappen.to_s.insert(-3, ".")
              uscent = item["prices"]["USD"]
              prices[itemid]["USD"] = uscent.to_s.insert(-3, ".")
              eucent = item["prices"]["EUR"]
              prices[itemid]["EUR"] = eucent.to_s.insert(-3, ".")
              aucent = item["prices"]["AUD"]
              prices[itemid]["AUD"] = aucent.to_s.insert(-3, ".")
            end

            response = HTTParty.get SHOP_URL
            document = Nokogiri::HTML(response.body)
            items = document.at('#ItemDefsRows')
            myitems = Hash.new
            items.search('.item_def_grid_item').each do |item|
              link = item.at('.item_def_icon_container/a').attr('href')
              id = link.match(/https:\/\/store.steampowered.com\/itemstore\/252490\/detail\/(?<id>\d+)\//)[:id]
              picture = item.at('.item_def_icon_container/a/img').attr('src')
              picture << ".png"
              name = item.at('.item_def_name/a').text
              name.strip!
              price = item.at('.item_def_price').text
              price.strip!
              myitems[id] = Hash.new
              myitems[id]["id"] = id
              myitems[id]["url"] = link
              myitems[id]["img"] = picture
              myitems[id]["name"] = name
              myitems[id]["prices"] = prices[id]
            end

            myitems.each do | index, remote_object |
              local_entry = feed.skins.where(skinid: remote_object["id"]).first_or_initialize
              local_entry.gameid = "252490"
              local_entry.name = remote_object["name"]
              local_entry.steamlink = remote_object["url"]
              local_entry.steampic = remote_object["img"]
              local_entry.price_chf = remote_object["prices"]["CHF"]
              local_entry.price_eur = remote_object["prices"]["EUR"]
              local_entry.price_usd = remote_object["prices"]["USD"]
              local_entry.price_aud = remote_object["prices"]["AUD"]
              local_entry.save!
              if local_entry.errors.any?
                local_entry.errors.each do |e|
                  @message << e.to_s
                end
              end
              @message << " --- Synced Remote Entry - #{remote_object["name"]} <br>"
            end
	  else
            @message << " --- skipping #{feed.title}, no gameid <br>"
	  end
	else
          @message << " --- skipping #{feed.title}, pullurl is no url <br>"
	end
      else
        @message << " --- skipping #{feed.title}, no pullurl <br>"
      end
    end
  end

  private
    def set_feed
      @feed = Feed.find(params[:id])
    end

    def feed_params
      params.require(:feed).permit(:title, :pullurl, :gameid)
    end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_form.html.erb
<%= form_with(model: feed, local: true) do |form| %>
  <% if feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :pullurl %>
    <%= form.text_field :pullurl %>
  </div>

  <div class="field">
    <%= form.label :gameid %>
    <%= form.text_field :gameid %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Feeds</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Pullurl</th>
      <th>Gameid</th>
      <th>Created</th>
      <th>Updated</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= feed.title %></td>
        <td><%= feed.pullurl %></td>
        <td><%= feed.gameid %></td>
        <td><%= feed.created_at %></td>
        <td><%= feed.updated_at %></td>
        <td><%= link_to 'Show', feed %></td>
        <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
        <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feed', new_feed_path %>

<% console %>

app/views/feeds/new.html.erb
<h1>New Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/refresh.html.erb
<%= @message %>

app/views/feeds/refresh_news.html.erb
<%= @message %>
<p id="notice"><%= notice %></p>

app/views/feeds/refresh_skins.html.erb
<%= @message %>
<p id="notice"><%= notice %></p>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @feed.title %>
</p>

<p>
  <strong>Pullurl:</strong>
  <%= @feed.pullurl %>
</p>

<p>
  <strong>Gameid:</strong>
  <%= @feed.gameid %>
</p>

<p> <%= link_to 'Show entries', feed_entries_path(@feed) %>
  | <%= link_to 'Show skins', feed_skins_path(@feed) %> </p>

<p> <%= link_to 'Edit', edit_feed_path(@feed) %>
  | <%= link_to 'Back', feeds_path %> <p>