config/routes.rb
Rails.application.routes.draw do
  root to: "feeds#index"

  resources :feeds do
    resources :entries
    resources :skins
  end

  get '/refresh_news', to: 'feeds#refresh_news'
  get '/refresh_skins', to: 'feeds#refresh_skins'
  get '/publish_news', to: 'entries#publish'
  get '/publish_skins', to: 'skins#publish'

end

app/models/entry.rb
require 'kramdown'
require 'nokogiri'

class Entry < ApplicationRecord
  belongs_to :feed

  ROLE_MENTION = ENV["NOTIFY_NEWS_ROLE"]
  DISCORD_REMOTE = ENV['DISCORD_REMOTE']

  def description_to_kramdown
    Kramdown::Document.new(description, :input => 'html').to_kramdown
  end

  def send_to_discord
    fragment = Nokogiri::HTML.fragment(description)
    img = fragment.css('img').first.attr('src')
    fragment.search('.//a').each {|x| x.remove}
    fragment.search('.//span').each {|x| x.remove}
    f = fragment.to_html
    k = Kramdown::Document.new(f, :input => 'html').to_kramdown
    k.sub!(/{.*}/, '')


    color = 15805500
    author = "XXXX"
    authorf = { name: 'Author', value: author, inline: true }
    time = "2019-07-21 01:31:02"
    timef = { name: 'Time', value: time, inline: true }
    ffields = [ authorf, timef ]
    thumb = "https://steamcdn-a.akamaihd.net/steam/apps/252490/capsule_231x87.jpg"
    thumbe = { url: thumb }
    imagee = { url: img }
    embededes = { title: title, url: link1, description: k, color: color, fields: ffields, thumbnail: thumbe, image: imagee }
    embededs = [ embededes ]

    conn = Faraday.new(
         url: DISCORD_REMOTE,
         headers: {'Content-Type' => 'application/json'}
    )
    resp = conn.post do |req|
      req.body = { username: "plebbot", embeds: embededs }.to_json
    end
  end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]
  before_action :set_feed, only: [:show, :edit, :update, :destroy, :new, :index]


  def index
    @entries = @feed.entries
  end

  def show
  end

  def new
    @entry = Entry.new
  end

  def edit
  end

  def create
    @entry = Entry.new(entry_params)

    if @entry.save
      redirect_to feed_entry_path(@feed, @entry), notice: 'Entry was successfully created.'
    else
      render :new 
    end
  end

  def update
    if @entry.update(entry_params)
      redirect_to feed_entry_path(@feed, @entry), notice: 'Entry was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    if @entry.destroy
      redirect_to feed_entries_url(@feed), notice: 'Entry was successfully destroyed.'
    end
  end

  def publish
    @entries = Entry.where(status: 1)
    if @entries
      @entries.each do | e |
        e.send_to_discord
        e.status = 2
        e.save!
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    def set_feed
      @feed = Feed.find(params[:feed_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:feed, :feed_id, :title, :description, :picture, :link1, :link2, :guid)
    end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.erb
<%= form_with(model: [feed, entry], local: true) do |form| %>
  <% if entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <%= form.hidden_field :feed_id, :value => feed.id %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.text_field :picture %>
  </div>

  <div class="field">
    <%= form.label :link1 %>
    <%= form.text_field :link1 %>
  </div>

  <div class="field">
    <%= form.label :link2 %>
    <%= form.text_field :link2 %>
  </div>

  <div class="field">
    <%= form.label :guid %>
    <%= form.text_field :guid %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Show', feed_entry_path(@feed, @entry) %> |
<%= link_to 'Back', feed_entries_path(@feed) %>

app/views/entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Entries</h1>

<table>
  <thead>
    <tr>
      <th>Feed</th>
      <th>Title</th>
      <th>Description</th>
      <th>Picture</th>
      <th>Link1</th>
      <th>Link2</th>
      <th>Guid</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= link_to @feed.title, feed_entry_path(@feed, entry) %></td>
        <td><%= entry.title %></td>
        <td><%= entry.description %></td>
        <td><%= entry.picture %></td>
        <td><%= entry.link1 %></td>
        <td><%= entry.link2 %></td>
        <td><%= entry.guid %></td>
        <td><%= entry.status %></td>
        <td><%= link_to 'Show', feed_entry_path(@feed, entry) %></td>
        <td><%= link_to 'Edit', edit_feed_entry_path(@feed, entry) %></td>
        <td><%= link_to 'Destroy', feed_entry_path(@feed, entry), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'To Feed', feed_path(@feed) %>

<%= link_to 'New Entry', new_feed_entry_path(@feed) %>

app/views/entries/new.html.erb
<h1>New Entry</h1>

<%= render 'form', entry: @entry, feed: @feed %>

<%= link_to 'Back', feed_entries_path(@feed) %>

app/views/entries/published.html.erb
<p id="notice"><%= notice %></p>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Feed:</strong>
  <%= link_to feed_entry_path(@feed, @entry) %>
</p>

<p>
  <strong>Title:</strong>
  <%= @entry.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @entry.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @entry.picture %>
</p>

<p>
  <strong>Link1:</strong>
  <%= @entry.link1 %>
</p>

<p>
  <strong>Link2:</strong>
  <%= @entry.link2 %>
</p>

<p>
  <strong>Guid:</strong>
  <%= @entry.guid %>
</p>

<%= link_to 'Edit', edit_feed_entry_path(@feed, @entry) %> |
<%= link_to 'Back', feed_entries_path(@feed) %>