config/routes.rb
Rails.application.routes.draw do
  root to: "feeds#index"

  resources :feeds do
    resources :entries
    resources :skins
  end

  get '/refresh_news', to: 'feeds#refresh_news'
  get '/refresh_skins', to: 'feeds#refresh_skins'
  get '/publish_news', to: 'entries#publish'
  get '/publish_skins', to: 'skins#publish'

end

app/models/skin.rb
class Skin < ApplicationRecord
  belongs_to :feed

  ROLE_MENTION = ENV["NOTIFY_SKINS_ROLE"]
  DISCORD_REMOTE = ENV["DISCORD_SKINS_CHANNEL_HOOK"]

  def item_to_emb
    { title: "New Skin #{name}",
      url: "#{steamlink}",
      description: "New Skin Released: #{name}, ID #{skinid}!\n<@&#{ROLE_MENTION}>",
      color: 2724948,
      fields: [
        { name: "Price CHF", value: "#{price_chf}", inline: true},
        { name: "Price EUR", value: "#{price_eur}", inline: true},
        { name: "Price AUD", value: "#{price_aud}", inline: true},
        { name: "Price USD", value: "#{price_usd}", inline: true}
      ],
      thumbnail: {
        url: "#{steampic}"
      }
    }
  end 


  def send_to_discord
    postcontent = [ item_to_emb ]
    postbody = { embeds: postcontent }

    conn = Faraday.new(
         url: DISCORD_REMOTE,
         headers: {'Content-Type' => 'application/json'}
    )
    resp = conn.post do |req|
      req.body = postbody.to_json
    end
  end
end

app/controllers/skins_controller.rb
class SkinsController < ApplicationController
  before_action :set_skin, only: [:show, :edit, :update, :destroy]
  before_action :set_feed, only: [:show, :edit, :update, :destroy, :new, :index]

  def index
    @skins = @feed.skins
  end

  def show
  end

  def new
    @skin = Skin.new
  end

  def edit
  end

  def create
    @skin = Skin.new(skin_params)

      if @skin.save
        redirect_to @skin, notice: 'Skin was successfully created.'
      else
        render :new
      end
  end

  def update
      if @skin.update(skin_params)
        redirect_to @skin, notice: 'Skin was successfully updated.'
      else
        render :edit
      end
  end

  def destroy
    if @skin.destroy
      redirect_to skins_url, notice: 'Skin was successfully destroyed.'
    end
  end

  def publish
    @skins = Skin.where(status: 1)
    if @skins
      @skins.each do | s |
	s.status = 2 if s.send_to_discord
	sleep 2 if s.save!
      end
    end
  end

  private
    def set_skin
      @skin = Skin.find(params[:id])
    end

    def set_feed
      @feed = Feed.find(params[:feed_id])
    end

    def skin_params
      params.require(:skin).permit(:feed, :feed_id, :status, :gameid, :skinid, :steamlink, :steampic, :name, :price_chf, :price_eur, :price_usd, :price_aud, :price_eur)
    end
end

app/helpers/skins_helper.rb
module SkinsHelper
end

app/views/skins/_form.html.erb
<%= form_with(model: [feed, skin], local: true) do |form| %>
  <% if skin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(skin.errors.count, "error") %> prohibited this skin from being saved:</h2>

      <ul>
      <% skin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :feed_id, :value => feed.id %>

  <div class="field">
    <%= form.label :feed_id %>
    <%= form.text_field :feed_id %>
  </div>

  <div class="field">
    <%= form.label :gameid %>
    <%= form.text_field :gameid %>
  </div>

  <div class="field">
    <%= form.label :skinid %>
    <%= form.text_field :skinid %>
  </div>

  <div class="field">
    <%= form.label :steamlink %>
    <%= form.text_field :steamlink %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status %>
  </div>

  <div class="field">
    <%= form.label :steampic %>
    <%= form.text_field :steampic %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price_chf %>
    <%= form.text_field :price_chf %>
  </div>

  <div class="field">
    <%= form.label :price_eur %>
    <%= form.text_field :price_eur %>
  </div>

  <div class="field">
    <%= form.label :price_usd %>
    <%= form.text_field :price_usd %>
  </div>

  <div class="field">
    <%= form.label :price_aud %>
    <%= form.text_field :price_aud %>
  </div>

  <div class="field">
    <%= form.label :price_eur %>
    <%= form.text_field :price_eur %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/skins/edit.html.erb
<h1>Editing Skin</h1>

<%= render 'form', skin: @skin %>

<%= link_to 'Show', feed_skin_path(@feed, @skin) %> |
<%= link_to 'Back', feed_skins_path(@feed) %>

app/views/skins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Skins</h1>

<table>
  <thead>
    <tr>
      <th>Feed</th>
      <th>Gameid</th>
      <th>Skinid</th>
      <th>Status</th>
      <th>Steamlink</th>
      <th>Steampic</th>
      <th>Name</th>
      <th>Price chf</th>
      <th>Price eur</th>
      <th>Price usd</th>
      <th>Price aud</th>
      <th>Price eur</th>
      <th>Created</th>
      <th>Updated</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @skins.each do |skin| %>
      <tr>
        <td><%= link_to @feed.title, feed_path(@feed) %></td>
        <td><%= skin.gameid %></td>
        <td><%= skin.skinid %></td>
        <td><%= skin.status %></td>
        <td><%= skin.steamlink %></td>
        <td><%= skin.steampic %></td>
        <td><%= skin.name %></td>
        <td><%= skin.price_chf %></td>
        <td><%= skin.price_eur %></td>
        <td><%= skin.price_usd %></td>
        <td><%= skin.price_aud %></td>
        <td><%= skin.price_eur %></td>
        <td><%= skin.created_at %></td>
        <td><%= skin.updated_at %></td>
        <td><%= link_to 'Show', skin %></td>
        <td><%= link_to 'Edit', edit_skin_path(skin) %></td>
        <td><%= link_to 'Destroy', skin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Skin', new_feed_skin_path(@feed) %>

app/views/skins/new.html.erb
<h1>New Skin</h1>

<%= render 'form', skin: @skin,  feed: @feed %>

<%= link_to 'Back', feed_skins_path(@feed) %>

app/views/skins/publish.html.erb
<p id="notice"><%= notice %></p>

app/views/skins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Feed:</strong>
  <%= link_to feed_entry_path(@feed, @entry) %>
</p>

<p>
  <strong>Gameid:</strong>
  <%= @skin.gameid %>
</p>

<p>
  <strong>Skinid:</strong>
  <%= @skin.skinid %>
</p>

<p>
  <strong>Steamlink:</strong>
  <%= @skin.steamlink %>
</p>

<p>
  <strong>Steampic:</strong>
  <%= @skin.steampic %>
</p>

<p>
  <strong>Name:</strong>
  <%= @skin.name %>
</p>

<p>
  <strong>Price chf:</strong>
  <%= @skin.price_chf %>
</p>

<p>
  <strong>Price eur:</strong>
  <%= @skin.price_eur %>
</p>

<p>
  <strong>Price usd:</strong>
  <%= @skin.price_usd %>
</p>

<p>
  <strong>Price aud:</strong>
  <%= @skin.price_aud %>
</p>

<p>
  <strong>Price eur:</strong>
  <%= @skin.price_eur %>
</p>

<%= link_to 'Edit', edit_feed_skin_path(@feed, @skin) %> |
<%= link_to 'Back', feed_skins_path(@feed) %>